__author__ = "AThousandYears"


class Devices:
    VOICE = 'VOICE'
    BASE_STATUS = 'BASE_STATUS'
    GESTURE = 'GESTURE'
    NECK = 'NECK'
    DOOR = 'DOOR'
    PEOPLE = 'PEOPLE'
    OBJECT = 'OBJECT'
    RIGHT_ARM = 'RIGHT_ARM'
    LEFT_ARM = 'LEFT_ARM'
    HEIGHT = 'HEIGHT'
    CIRCLE_DETECT = 'CIRCLE_DETECT'
    JOY = 'JOY'
    RECOGNIZE_OBJECTS = 'RECOGNIZE_OBJECTS'
    OBJECT_3DS_DETECTOR = 'OBJECT_3DS_DETECTOR'
